title: "Materials Informatics Lab, AZ"
url: "https://materials-informatics-az.github.io"
baseurl: ""

markdown: kramdown

tracking_id: "UA-61278008-2"

sass:
    style: compressed
    sass_dir: _sass
